exports.tap = [
  '  Usage: clever-generate \\[options\\] \\[command\\]',
  '',
  '',
  '  Commands:',
  '',
  '    service \\[options\\] <name>       Generates a service as <name> within .*services',
  '    services \\[options\\] <names>     Generates services specified with <name ...> within .*services',
  '    controller \\[options\\] <name>    Generates a controller as <name> within .*controllers',
  '    controllers \\[options\\] <names>  Generates controllers specified with <name ...> within .*controllers',
  '    model \\[options\\] <name>         Generates a model as <name> within .*models',
  '    models \\[options\\] <names>       Generates models specified with <name ...> within .*models',
  '    task \\[options\\] <name>          Generates a task as <name> within .*tasks',
  '    tasks \\[options\\] <names>        Generates tasks specified with <name ...> within .*tasks',
  '    view \\[options\\] <name>          Generates a view as <name> within .*views',
  '    views \\[options\\] <names>        Generates views specified with <name ...> within .*views',
  '    factory \\[options\\] <name>       Generates a factory as <name> within .*factories',
  '    factories \\[options\\] <names>    Generates factories specified with <name ...> within .*factories',
  '    service \\[options\\] <name>       Generates a service as <name> within .*services',
  '    services \\[options\\] <names>     Generates services specified with <name ...> within .*services',
  '    directive \\[options\\] <name>     Generates a directive as <name> within .*directives',
  '    directives \\[options\\] <names>   Generates directives specified with <name ...> within .*directives',
  '    test \\[options\\] <name>          Generates a test t as <name> within .*tests',
  '    tests \\[options\\] <names>        Generates test specified with <name ...> within .*tests',
  '',
  '  Options:',
  '',
  '    -h, --help     output usage information',
  '    -v, --verbose  verbose output useful for debugging',
  '    -V, --version  output the version number',
  '',
  '  Example:',
  '',
  '    clever generate model users',
  '    clever generate controller users',
  '    clever g controller users',
  '    clever g controllers users auth email'
];
