exports.tap = [
  '  Usage: clever-init \\[options\\] \\[command\\]',
  '',
  '  Commands:',
  '',
  '    <project>               Creates a project named <project>',
  '',
  '  Options:',
  '',
  '    -h, --help         output usage information',
  '    --skip-protractor  Skips installing protractor',
  '    --allow-root       Tells Bower to allow root',
  '    -V, --version      output the version number',
  '',
  '  Examples:',
  '    clever init my-project',
  '    clever init project-frontend frontend',
  '    clever init my-project-everything backend frontend',
  '',
  '  Installing specific versions:',
  '    clever init my-project backend\\@<version>',
  '    clever init my-project frontend\\@<version>'
];
