exports.tap = [
  '  Usage: clever-setup \\[options\\]',
  '',
  '  Options:',
  '',
  '    -h, --help         output usage information',
  '    -A, --allow-root       allow root for bower',
  '    -S, --skip-protractor  skips installing protractor \\(Frontend only\\)',
  '    -v, --verbose          verbose output useful for debugging',
  '    -V, --version      output the version number',
  '',
  '  Description:',
  '',
  '    Installs all NPM and Bower components for each module as well as building bundleDependencies.',
  '    This command will also install Protractor unless explicitly skipping.',
  '',
  '  Examples:',
  '',
  '    clever setup'
];
