exports.tap = [
  '  Usage: clever-test \\[options\\] \\[command\\]',
  '',
  '  Commands:',
  '',
  '    e2e        Runs e2e tests',
  '    unit       Runs unit tests',
  '    coverage   Generates unit test coverage reports.',
  '',
  '  Options:',
  '',
  '    -h, --help     output usage information',
  '    -V, --version  output the version number',
  '',
  '  Examples:',
  '',
  '    clever test coverage',
  '    clever test e2e',
  '    clever test unit'
];
